# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# for simplicity we are compiling and testing everything on the Ubuntu environment only.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Rust environment
        uses: ./.github/actions/prepare-rust

      - name: Run cargo check
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Rust environment
        uses: ./.github/actions/prepare-rust

      - name: Run cargo test
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: test

  lints:
    # disable because there are clippy warnings on the upstream code
    if: ${{ false }}     
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Rust environment
        uses: ./.github/actions/prepare-rust

      - name: Run cargo fmt
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: clippy
          args: -- -D warnings

